/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../src/types/schema.json
export type PrimaryButton = {
  text?: string;
  link?: string;
};

export type SecondaryButton = {
  text?: string;
  link?: string;
};

export type Slot = {
  _id: string;
  _type: "slot";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  availableTimes?: Array<string>;
  isFullyBooked?: boolean;
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  rating?: 1 | 2 | 3 | 4 | 5;
  content?: string;
  reviewDate?: string;
  approved?: boolean;
};

export type ContactMessage = {
  _id: string;
  _type: "contactMessage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  message?: string;
  createdAt?: string;
  status?: "new" | "read" | "replied";
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type Appointment = {
  _id: string;
  _type: "appointment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clientName?: string;
  email?: string;
  phone?: string;
  service?: ServiceReference;
  preferredDate?: string;
  meetingType?: "online" | "in-person";
  status?: "pending" | "confirmed" | "cancelled" | "completed";
  notes?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  position?: number;
  title?: string;
  meetingType?: "online" | "in-person";
  duration?: 10 | 30 | 60 | 90;
  price?: number;
  priceDisplay?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  logoWidth?: number;
  logoHeight?: number;
  googleAnalyticsId?: string;
};

export type FooterSettings = {
  _id: string;
  _type: "footerSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  description?: string;
  socialLinks?: {
    facebook?: string;
    instagram?: string;
    linkedin?: string;
    youtube?: string;
    tiktok?: string;
    twitter?: string;
    pinterest?: string;
  };
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    title?: string;
    subtitle?: string;
  };
  contactInfo?: {
    phone?: {
      number?: string;
      hours?: string;
    };
    email?: {
      address?: string;
    };
    location?: {
      street?: string;
      note?: string;
    };
  };
  form?: {
    title?: string;
    subtitle?: string;
    responseTimeNote?: string;
    successMessage?: string;
  };
  map?: {
    showMap?: boolean;
    embedUrl?: string;
    coordinates?: {
      lat?: number;
      lng?: number;
    };
  };
  seo?: SeoFields;
};

export type SeoFields = {
  _type: "seoFields";
  metaTitle?: string;
  metaDescription?: string;
  keywords?: Array<string>;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  canonicalUrl?: string;
  noIndex?: boolean;
};

export type BookingPage = {
  _id: string;
  _type: "bookingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    title?: string;
    subtitle?: string;
  };
  instructions?: PortableTextContent;
  confirmationMessages?: {
    successTitle?: string;
    successMessage?: string;
  };
  seo?: SeoFields;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type PortableTextContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "h5" | "blockquote" | "lead";
      listItem?: "bullet" | "number" | "check";
      markDefs?: Array<
        | {
            href?: string;
            openInNewTab?: boolean;
            _type: "link";
            _key: string;
          }
        | {
            reference?: PageReference;
            _type: "internalLink";
            _key: string;
          }
        | {
            color?: "pink" | "violet" | "blue" | "green" | "red" | "gray";
            _type: "textColor";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      size?: "small" | "medium" | "large" | "full" | "original";
      alignment?: "left" | "center" | "right";
      float?: "none" | "left" | "right";
      borderRadius?: "none" | "small" | "medium" | "large" | "full";
      shadow?: boolean;
      border?: boolean;
      link?: string;
      customClass?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & TableBlock)
  | ({
      _key: string;
    } & CodeBlock)
  | ({
      _key: string;
    } & CalloutBlock)
  | ({
      _key: string;
    } & DividerBlock)
>;

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    title?: string;
    subtitle?: string;
    badge?: string;
  };
  emptyStateMessage?: string;
  seo?: SeoFields;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    title?: string;
    subtitle?: string;
  };
  bio?: {
    profileImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    experienceBadge?: {
      number?: string;
      label?: string;
    };
    name?: string;
    content?: PortableTextContent;
  };
  credentials?: Array<{
    icon?:
      | "FaGraduationCap"
      | "FaHeart"
      | "FaCertificate"
      | "FaAward"
      | "FaBook"
      | "FaStethoscope";
    iconColor?: "pink" | "violet" | "blue" | "green";
    title?: string;
    description?: string;
    _key: string;
  }>;
  values?: {
    sectionTitle?: string;
    items?: Array<
      {
        _key: string;
      } & ValueCard
    >;
  };
  cta?: CtaBlock;
  seo?: SeoFields;
};

export type CtaBlock = {
  _type: "ctaBlock";
  heading?: string;
  description?: string;
  primaryButton?: PrimaryButton;
  secondaryButton?: SecondaryButton;
  style?: "gradient-pink-violet" | "light-gray" | "white";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    badge?: string;
    title?: string;
    highlightedText?: string;
    subtitle?: string;
    heroImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    primaryCTA?: {
      text?: string;
      link?: string;
    };
    secondaryCTA?: {
      text?: string;
      link?: string;
    };
    availabilityNote?: string;
  };
  intro?: {
    heading?: string;
    content?: PortableTextContent;
    linkText?: string;
    linkUrl?: string;
  };
  servicesOverview?: {
    sectionTitle?: string;
    sectionSubtitle?: string;
    serviceCards?: Array<{
      icon?:
        | "FaHandsHelping"
        | "FaBaby"
        | "FaCalendarCheck"
        | "FaHeart"
        | "FaStar"
        | "FaGraduationCap"
        | "FaShieldAlt"
        | "FaUsers"
        | "FaLightbulb"
        | "FaCheckCircle"
        | "FaStethoscope"
        | "FaBook"
        | "FaChalkboardTeacher"
        | "FaClock"
        | "FaVideo"
        | "FaPhone"
        | "FaEnvelope"
        | "FaMapMarkerAlt"
        | "FaBox"
        | "FaAward";
      title?: string;
      description?: string;
      link?: string;
      _key: string;
    }>;
  };
  testimonials?: {
    sectionTitle?: string;
    showTestimonials?: boolean;
    maxCount?: number;
  };
  seo?: SeoFields;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  title?: string;
  excerpt?: string;
  publishedAt?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  content?: PortableTextContent;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    keywords?: Array<string>;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    canonicalUrl?: string;
    noIndex?: boolean;
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type DividerBlock = {
  _type: "dividerBlock";
  style?: "line" | "dotted" | "dashed" | "space";
};

export type CalloutBlock = {
  _type: "calloutBlock";
  type?: "info" | "warning" | "success" | "error" | "tip";
  title?: string;
  content?: string;
};

export type CodeBlock = {
  _type: "codeBlock";
  code?: string;
  language?:
    | "html"
    | "css"
    | "javascript"
    | "typescript"
    | "json"
    | "plaintext";
  renderAsHtml?: boolean;
  showLineNumbers?: boolean;
};

export type TableBlock = {
  _type: "tableBlock";
  caption?: string;
  rows?: Array<
    {
      _key: string;
    } & TableRow
  >;
  hasHeaderRow?: boolean;
  style?: "default" | "striped" | "bordered" | "compact";
};

export type TableRow = {
  _type: "tableRow";
  cells?: Array<
    {
      _key: string;
    } & TableCell
  >;
};

export type TableCell = {
  _type: "tableCell";
  content?: string;
  isHeader?: boolean;
};

export type ValueCard = {
  _type: "valueCard";
  icon?:
    | "FaHeart"
    | "FaHandsHelping"
    | "FaBaby"
    | "FaGraduationCap"
    | "FaStar"
    | "FaCalendarCheck"
    | "FaShieldAlt"
    | "FaUsers"
    | "FaLightbulb"
    | "FaCheckCircle"
    | "FaStethoscope"
    | "FaBook"
    | "FaChalkboardTeacher"
    | "FaClock"
    | "FaVideo"
    | "FaPhone"
    | "FaEnvelope"
    | "FaMapMarkerAlt"
    | "FaBox"
    | "FaAward";
  title?: string;
  description?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PrimaryButton
  | SecondaryButton
  | Slot
  | Review
  | ContactMessage
  | ServiceReference
  | Appointment
  | SanityImageAssetReference
  | Service
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSettings
  | FooterSettings
  | ContactPage
  | SeoFields
  | BookingPage
  | PageReference
  | PortableTextContent
  | ServicesPage
  | AboutPage
  | CtaBlock
  | HomePage
  | Page
  | Slug
  | DividerBlock
  | CalloutBlock
  | CodeBlock
  | TableBlock
  | TableRow
  | TableCell
  | ValueCard
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;
