import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import CookieBanner from '@/components/CookieBanner';
import GoogleAnalytics from '@/components/GoogleAnalytics';
import { client, urlFor } from '@/lib/sanity.client';
import { groq } from 'next-sanity';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface SiteSettingsData {
  siteName?: string;
  logo?: {
    asset?: {
      _ref: string;
    };
    alt?: string;
  };
  logoWidth?: number;
  logoHeight?: number;
  googleAnalyticsId?: string;
}

async function getSiteSettings(): Promise<SiteSettingsData | null> {
  return client.fetch(groq`*[_type == "siteSettings" && _id == "siteSettings"][0]{
    siteName,
    logo {
      asset,
      alt
    },
    logoWidth,
    logoHeight,
    googleAnalyticsId
  }`);
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const siteSettings = await getSiteSettings();

  // Prepare site settings for Navbar (client component)
  const navbarSettings = siteSettings
    ? {
        siteName: siteSettings.siteName,
        logoUrl: siteSettings.logo?.asset
          ? urlFor(siteSettings.logo).url()
          : undefined,
        logoAlt: siteSettings.logo?.alt,
        logoWidth: siteSettings.logoWidth,
        logoHeight: siteSettings.logoHeight
      }
    : null;

  return (
    <html lang="hu">
      <head>
        <GoogleAnalytics measurementId={siteSettings?.googleAnalyticsId} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Navbar siteSettings={navbarSettings} />
        <main className="flex-grow pt-20">{children}</main>
        <Footer />
        <CookieBanner />
      </body>
    </html>
  );
}
